version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install requests beautifulsoup4
      - wget https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
      - unzip terraform_1.0.11_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
      
  pre_build:
    commands:
      - echo Starting pre-build phase...
      - echo "Verifying repository structure..."
      - cd environments/$ENV
      - terraform init -input=false
      
  build:
    commands:
      - echo Starting build phase...
      - terraform plan -out=tfplan -input=false
      - terraform apply -auto-approve tfplan
      - echo "Determining environment-specific variables"
      - BUCKET_ID=$(terraform output -raw website_bucket_id || echo "bucket-not-found")
      - WEBSITE_URL=$(terraform output -raw website_endpoint || echo "url-not-found")
      - echo "Website URL $WEBSITE_URL"
      - echo "Bucket ID $BUCKET_ID"
      - aws s3 cp ../../index.html s3://$BUCKET_ID/
      - aws s3 cp ../../error.html s3://$BUCKET_ID/
      
  post_build:
    commands:
      - echo Starting tests...
      - cd ../../tests
      - export WEBSITE_URL=http://$WEBSITE_URL
      - echo "Testing website at URL $WEBSITE_URL"
      - python test_website.py || echo "Tests failed but continuing build"
      - echo Tests completed

artifacts:
  files:
    - index.html
    - error.html
    - appspec.yml
    - scripts/**/*
  base-directory: '.'