version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install requests beautifulsoup4
      - >-
        wget
        https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
      - unzip terraform_1.0.11_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  pre_build:
    commands:
      - echo Starting pre-build phase...
      - echo "Verifying repository structure..."
      - 'test -f index.html || { echo "index.html is missing!"; exit 1; }'
      - 'test -f error.html || { echo "error.html is missing!"; exit 1; }'
      - >-
        test -d environments/$ENV || { echo "Environment directory $ENV
        missing!"; exit 1; }
      - cd environments/$ENV
      - terraform init -input=false
  build:
    commands:
      - echo Starting build phase...
      - terraform plan -out=tfplan -input=false
      - terraform apply -auto-approve tfplan
      - |
        if [ "$ENV" = "prod" ]; then
          BUCKET_ID=$(terraform output -raw prod_website_bucket_id 2>/dev/null || terraform output -raw website_bucket_id)
          WEBSITE_URL=$(terraform output -raw website_endpoint 2>/dev/null || terraform output -raw cloudfront_domain_name)
        else
          BUCKET_ID=$(terraform output -raw website_bucket_id)
          WEBSITE_URL=$(terraform output -raw website_endpoint)
        fi
      - echo "Website URL: $WEBSITE_URL"
      - echo "Bucket ID: $BUCKET_ID"
      - 'aws s3 cp ../../index.html s3://$BUCKET_ID/'
      - 'aws s3 cp ../../error.html s3://$BUCKET_ID/'
  post_build:
    commands:
      - echo Starting tests...
      - cd ../../tests
      - 'export WEBSITE_URL=http://$WEBSITE_URL'
      - echo "Testing website at URL: $WEBSITE_URL"
      - |
        if ! python test_website.py; then
          echo "Tests failed! Website does not meet requirements."
          echo "Please check the HTML content and try again."
          exit 1
        fi
      - echo Tests completed successfully!
artifacts:
  files:
    - index.html
    - error.html
    - appspec.yml
    - scripts/**/*
  base-directory: .
